import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import "azure-maps-control/dist/atlas.min.css";
import 'mapbox-gl/dist/mapbox-gl.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "T2050",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: {children: React.ReactNode;}) {
  return (
    <html lang="en">
      <head>
        {/* Load the script without event handlers */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </html>
  );
}
